### ISSUE TITLE
App doesn't compile for android

### ISSUE THREAD

**Issue by mabu-dev** [kelvin147789/Flutter_UI_Reality#2]
I compiled on iOS successfully. But it hangs during install on Android. 

Launching lib/main.dart on SM A105F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk. - **it stops here.**

**Comment by okok147** [comment]
If possible, please try Pixel  3a XL API 29. It stops.

Or, I would rebuild the project in the future. Thank you for issuing.
